import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PePe Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <main className="border mx-5 p-4 scroll-smooth" >
        
      <Header />
         {children}
     <footer className="text-gray-500 border-t-2 p-7 text-center ">
           &copy; 2024 All rights reserved
      </footer>
      </main> 
      </body>
    </html>
  );
}
